import {
  ArchiveIcon,
  AtomIcon,
  BanknoteIcon,
  BotIcon,
  BoxesIcon,
  BrainIcon,
  BriefcaseIcon,
  BugIcon,
  CalendarClockIcon,
  CaptionsIcon,
  CompassIcon,
  ContainerIcon,
  CpuIcon,
  DatabaseIcon,
  DownloadIcon,
  FileTextIcon,
  FilmIcon,
  FlaskConicalIcon,
  Gamepad2Icon,
  GaugeIcon,
  GitBranchIcon,
  GlobeIcon,
  HammerIcon,
  HardDriveIcon,
  ImageIcon,
  LayersIcon,
  LayoutDashboardIcon,
  type LucideIcon,
  MailIcon,
  MonitorIcon,
  MusicIcon,
  PackageIcon,
  PaletteIcon,
  PlayIcon,
  PlugIcon,
  PuzzleIcon,
  ScrollTextIcon,
  SearchIcon,
  ServerIcon,
  ShapesIcon,
  ShieldIcon,
  SmartphoneIcon,
  SparklesIcon,
  TargetIcon,
  TerminalIcon,
  TvIcon,
  WifiIcon,
  WorkflowIcon,
} from "lucide-react";
import type { FC } from "react";

/**
 * The server names a topic's icon; the whitelist here turns that name into a
 * component so an unexpected name can never crash the page.
 */
const ICONS: Record<string, LucideIcon> = {
  archive: ArchiveIcon,
  atom: AtomIcon,
  banknote: BanknoteIcon,
  bot: BotIcon,
  boxes: BoxesIcon,
  brain: BrainIcon,
  briefcase: BriefcaseIcon,
  bug: BugIcon,
  "calendar-clock": CalendarClockIcon,
  captions: CaptionsIcon,
  compass: CompassIcon,
  container: ContainerIcon,
  cpu: CpuIcon,
  database: DatabaseIcon,
  download: DownloadIcon,
  "file-text": FileTextIcon,
  film: FilmIcon,
  "flask-conical": FlaskConicalIcon,
  "gamepad-2": Gamepad2Icon,
  gauge: GaugeIcon,
  "git-branch": GitBranchIcon,
  globe: GlobeIcon,
  hammer: HammerIcon,
  "hard-drive": HardDriveIcon,
  image: ImageIcon,
  layers: LayersIcon,
  "layout-dashboard": LayoutDashboardIcon,
  mail: MailIcon,
  monitor: MonitorIcon,
  music: MusicIcon,
  package: PackageIcon,
  palette: PaletteIcon,
  play: PlayIcon,
  plug: PlugIcon,
  puzzle: PuzzleIcon,
  "scroll-text": ScrollTextIcon,
  search: SearchIcon,
  server: ServerIcon,
  shapes: ShapesIcon,
  shield: ShieldIcon,
  smartphone: SmartphoneIcon,
  sparkles: SparklesIcon,
  target: TargetIcon,
  terminal: TerminalIcon,
  tv: TvIcon,
  wifi: WifiIcon,
  workflow: WorkflowIcon,
};

type Props = {
  name: string;
  className?: string;
};

export const TopicIcon: FC<Props> = ({ name, className }) => {
  const Icon = ICONS[name] ?? BoxesIcon;
  return <Icon className={className} />;
};
