/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdSessionRouteImport } from './routes/projects/$projectId/session'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdSessionRoute =
  ProjectsProjectIdSessionRouteImport.update({
    id: '/projects/$projectId/session',
    path: '/projects/$projectId/session',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/login': typeof LoginRoute
  '/topics': typeof TopicsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/session': typeof ProjectsProjectIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/login': typeof LoginRoute
  '/topics': typeof TopicsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/session': typeof ProjectsProjectIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/login': typeof LoginRoute
  '/topics': typeof TopicsRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/session': typeof ProjectsProjectIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/login'
    | '/topics'
    | '/projects/'
    | '/projects/$projectId/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/login'
    | '/topics'
    | '/projects'
    | '/projects/$projectId/session'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/login'
    | '/topics'
    | '/projects/'
    | '/projects/$projectId/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRoute
  LoginRoute: typeof LoginRoute
  TopicsRoute: typeof TopicsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdSessionRoute: typeof ProjectsProjectIdSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/session': {
      id: '/projects/$projectId/session'
      path: '/projects/$projectId/session'
      fullPath: '/projects/$projectId/session'
      preLoaderRoute: typeof ProjectsProjectIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRoute,
  LoginRoute: LoginRoute,
  TopicsRoute: TopicsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdSessionRoute: ProjectsProjectIdSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
